service: AutomationStopRandom

provider:
  name: aws
  runtime: python3.8
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "ec2:DescribeInstances"
        - "ec2:StopInstances"
        - "ec2:StartInstances"
      Resource: "*"

functions:
  hello:
    handler: handler.entry_point
    timeout: 300

